kike-canaries/canairio_sensorlib

- examples/platformio/platformio.ini
- examples/platformio/src/main.cpp
- src/Sensors.cpp
- src/Sensors.hpp
> added debug mode via setter with ESP8266 compatibility

- .github/workflows/platformio.yml
- Sensors.cpp
- Sensors.hpp
> added missing implementations for pm1 and pm4 on sps30

- examples/platformio/platformio.ini
- library.json
Added Manifiest for PlatformIO package and library registry, also maybe it works for Arduino Library (untested)
It fix the issues #1 and #2
> Platformio registry issue1

- .gitignore
- README.md
- examples/basic/basic.ino
- examples/platformio/README.md
- examples/platformio/platformio.ini
- library.json
- library.properties
Added basic example for Arduino framework and documentation for `arduino-cli`.
Resolve issue #3 
Only `platformio` and `arduino-cli` with target esp32 board
> Arduino example

- Sensors.cpp
- Sensors.hpp
- examples/basic/basic.ino
- examples/platformio/platformio.ini
- examples/platformio/src/main.cpp
- library.json
- library.properties
Refactor sensor type enum for give fix to issue #16 also some changes on examples was added
> Refactor enum generic #16

- Sensors.cpp
- examples/basic_esp8266/basic_esp8266.ino
- examples/platformio/platformio.ini
- examples/platformio/src/main.cpp
- library.json
- library.properties
> Samsung pm1 init fix

- Sensors.cpp
- Sensors.hpp
> Support of new sensors H&T: bme280, aht10, sht31, dht22

- .github/workflows/platformio.yml
- .travis.yml
- fix travis CI root build issue
- fix github workflow root build issue
> fixed missing root build on workflows

- examples/platformio/src/main.cpp
- src/Sensors.cpp
SDC30 init problem resolved: CO2SCD30Init()
Minor changes
Tested on:
PM
Honeywell HMPA115S0: OK
Plantower PMSA003: OK
Panasonic SN-GCJA5L: OK
Sensirion SPS30: OK
CO2
Winsen MH-Z14A: OK
Cubic CM1106: OK
Sensirion SCD30: OK
Humidity/temperature
Asair AM2320: OK
Asair AHT10: OK
Aosong DHT11: OK
Aosong DHT22: OK
Bosh BME280: OK
Sensirion SHT31: OK
> Some minor changes and routine SDC30 init

- src/Sensors.cpp
- src/Sensors.hpp
Reformat code to clang Google Style.
> Clang format fixes

- src/Sensors.cpp
- src/Sensors.hpp
SCD30 as i2c sensor, not type.
Error:
[W][SENSORS] PM sensor not configured!
> SCD30 as i2c sensor, not type

- .travis.yml
> fixed python version on Travis CI deploy file

- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Cm1106uartlib

- src/Sensors.cpp
- src/Sensors.hpp
> CanAirIO sensorlib RC2 v0.2.1

- README.md
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Scd30 calibrate and stime

- platformio.ini
- src/Sensors.cpp
> fixed possible UART issue. Conflict with i2c in Panasonic

- src/Sensors.cpp
> fixed publication issue on Panasonic i2c sensors

- platformio.ini
> updated all dependencies

- src/Sensors.cpp
> added S8 bg calibration call suggested from @jcomas

- examples/co2_cm1106/co2_cm1106_altitude_comp.ino
- examples/co2_scd30/co2_scd30_altitude_comp.ino
- src/Sensors.cpp
- src/Sensors.hpp
Altitude compensation examples CM1106 and SCD30
> Altitude compensation examples CM1106 and SCD30

- src/Sensors.cpp
> added power saving optimization for sps30 with long stime

- README.md
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
> fixed possible nullptr exception on error callback

- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
this PR fixed issue #91 and remove the Adafruit AM2320 sensor library (it has time issues)
> Fix am2320 temp

- library.json
- library.properties
- src/Sensors.cpp
> Fix pm10gcja5

- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Fix issue 88 (S8_UART ibrary migration)

- library.json
- library.properties
- src/Sensors.cpp
The altitude value setter, when we did the integration with SCD4x was in wrong place
> fixed issue, setters was into the validation

- src/Sensors.cpp
Fixes a bug with comparation with floats
As discussed at: https://t.me/canairio/18540
> Fix bug with float comparation 

- README.md
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Bme280 issues

- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
> Fix sensorlib issue #101

- README.md
- examples/advanced_sensirion/sensirion.ino
- examples/basic/basic.ino
- examples/basic_esp8266/basic_esp8266.ino
- examples/co2_cm1106/co2_cm1106.ino
- examples/co2_cm1106/co2_cm1106_altitude_comp.ino
- examples/co2_mhz19/co2_mhz19.ino
- examples/co2_scd30/co2_scd30.ino
- examples/co2_scd30/co2_scd30_altitude_comp.ino
- examples/co2_scd4x/co2_scd4x.ino
- examples/platformio/src/main.cpp
- examples/pm_sds011/pm_sds011.ino
- examples/sps30i2c/sps30i2c.cpp
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Fix issue 102

- src/Sensors.cpp
> Debug mode improvements

- deploy.sh
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Release 0.4.2

- README.md
- library.json
- library.properties
- src/Sensors.cpp
- src/Sensors.hpp
> added ESP32PICOD4 board. 

- README.md
- examples/advanced_multivariable/platformio.ini
- examples/advanced_multivariable/src/main.cpp
- examples/basic/basic.ino
- examples/basic_esp8266/basic_esp8266.ino
- examples/co2_senseairs8/co2_senseairs8.ino
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
This version added new getters to have the current status of each unit of each sensor connected to the device in real time. 
```cpp
uint8_t getUnitsRegisteredCount();
bool isUnitRegistered(UNIT unit);
String getUnitName(UNIT unit);
String getUnitSymbol(UNIT unit);
int getNextUnit();
uint32_t getUnitValue(UNIT unit);
```
> Variables vector

- README.md
- examples/advanced_multivariable/src/main.cpp
- examples/advanced_sensirion/sensirion.ino
- examples/basic/basic.ino
- examples/basic_esp8266/basic_esp8266.ino
- examples/co2_cm1106/co2_cm1106.ino
- examples/co2_mhz19/co2_mhz19.ino
- examples/co2_scd30/co2_scd30.ino
- examples/co2_scd30/co2_scd30_altitude_comp.ino
- examples/co2_scd4x/co2_scd4x.ino
- examples/co2_senseairs8/co2_senseairs8.ino
- examples/platformio/src/main.cpp
- examples/pm_sds011/pm_sds011.ino
- examples/sps30i2c/sps30i2c.cpp
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> M5stack two wires

- doxygen.conf
- examples/co2_cm1106/co2_cm1106_altitude_comp.ino
- examples/m5atom/platformio.ini
- examples/m5atom/src/main.cpp
- examples/m5coreink/platformio.ini
- examples/m5coreink/src/main.cpp
- library.json
- library.properties
- src/Sensors.cpp
- src/Sensors.hpp
> Fix issue 125 uart

- README.md
- src/Sensors.cpp
- src/Sensors.hpp
> added sea level pressure setter and improve documentation

- src/Sensors.hpp
Added M5Stack Stamp PICO D4 board
> Add M5PICOD4 board

- README.md
- src/Sensors.cpp
- src/Sensors.hpp
> Solar station flag

- examples/platformio/platformio.ini
- examples/wio_terminal/.gitignore
- examples/wio_terminal/platformio.ini
- examples/wio_terminal/src/main.cpp
> Wio terminal initial support

- doxygen.conf
- library.json
- library.properties
- src/Sensors.cpp
- src/Sensors.hpp
> Fix m5stickc zero units

- examples/advanced_sensirion/platformio.ini
- library.json
- library.properties
- platformio.ini
- src/Sensors.cpp
- src/Sensors.hpp
> Fix issue 157 sps30

- examples/advanced_multivariable/src/main.cpp
- src/Sensors.cpp
- unified-lib-deps.ini
> Av fix 184 bme280

- README.md
Just to fix the CO2 Gadget name ;-)
> Update CO2 Gadget name in README

- library.json
- library.properties
- src/Sensors.cpp
- src/Sensors.hpp
Added missing register validation like sen5x.
> Add register validation

- src/Sensors.cpp
- src/Sensors.hpp
Please review full details in the #203 issue.
> Fix 203 toffset
